### ISSUE TITLE
Unable to save CSP XSL files via docker

### ISSUE THREAD

**Issue by mvhenderson** [intersystems-community/vscode-objectscript#886]
All of my projects that use the `/csp/xslt` application can no longer make changes to the XSL files, instead returning the following error `ERROR #16006: Document 'test.xsl' name is invalid`.   This was working a few weeks ago - did something change recently? 

VSCode: Version: 1.64.2
Docker: 20.10.12
ObjectScript extension: v1.4.3
LanguageServer extension: v1.2.9
ServerManager extension: v2.0.7

Steps to reproduce:

1. Save the attached docker-compose into a clean directory
2. Create subdirectory named `durable` then start it up with `docker-compose up -d`
3. reset super users and point /csp/xslt to HSCUSTOM

```
docker-compose exec iris iris session iris

zn "%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")
zn "HSCUSTOM"
write ##class(HS.Util.SystemAPI).Invoke("AddCSPXSLTapplication", "%")
write ##class(HS.Util.SystemAPI).Invoke("UpdateCSPApp", "HSCUSTOM", "/csp/xslt", $LB($LB("NameSpace","HSCUSTOM")))
```

4. Open VSCode to your folder and connect to the docker instance (sample folder settings.json attached)
5. Use the ObjectScript explorer to export an existing `/csp/xslt` XSL file then try to edit it from the `src` folder; it fails
6. Create a new XSL file (eg `./src/csp/xslt/text.xsl`) then try to edit it; it fails

docker-compose.yml

``` yaml
version: "2.2"
services:
  iris:
    container_name: test-iris-xsl
    init: true
    image: store/intersystems/irishealth-community:2021.2.0.649.0
    volumes:
      - .:/iris
    environment:
     - ISC_DATA_DIRECTORY=/iris/durable
    ports:
     - 9092:52773
```

.vscode/settions.json

``` json
{
    "objectscript.conn": {
      "active": true,
      "host": "localhost",
      "port": 9092,
      "username": "_SYSTEM",
      "password": "SYS",
      "ns": "HSCUSTOM",
      "docker-compose": {
        "service": "iris",
        "internalPort": 52773,
        "file": "docker-compose.yml"
      }
    },
    "objectscript.overwriteServerChanges": true
  }
```
